### ISSUE TITLE
Events on Sunday don't appear on weekly view

### ISSUE THREAD

**Issue by ahosgood** [MashSoftware/time-tracker#59]
**Describe the bug**
Events that begin on a Sunday don't appear on the list of events for the week. They are actually recorded and accessible via the "Tags" view.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create an entry that begins on a Sunday
2. Go to the weekly view for that Sunday
3. Your event is not shown

**Expected behaviour**
The event is displayed

**Additional context**
It looks like the last day of the week is defined correctly here: https://github.com/MashSoftware/the-button/blob/8a75f1075809974b77fb862e541de7298433a36b/app/entry/routes.py#L39
...but when the query is built it includes entries that are started "up to" that day: https://github.com/MashSoftware/the-button/blob/8a75f1075809974b77fb862e541de7298433a36b/app/entry/routes.py#L59
This might exclude all events started on a Sunday after 00:00.

**Comment by matthew-shaw** [comment]
Thanks for raising this @ahosgood. You're right, it was up to midnight on the 7th day of the week. I've resolved it by adding a timedelta of 23 hours, 59 mins and 59 seconds to include everything on the last day of the week. Will be closed in PR #61
